# Generated by Django 5.0.6 on 2024-07-01 00:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(help_text='Ingresa el RUT en el formato 12345678-9 o 12345678-K.', max_length=12, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='El RUT debe tener el formato 12345678-9 o 12345678-K.', regex='^\\d{8}-[\\dKk]$')])),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(help_text='Ingresa el número de teléfono sin espacios ni guiones.', max_length=15, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe contener entre 9 y 15 dígitos sin espacios ni guiones.', regex='^\\d{9,15}$')])),
                ('direccion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foto_url', models.URLField(blank=True, null=True)),
                ('talla', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='mk.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='mk.orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mk.producto')),
            ],
        ),
    ]
