# Generated by Django 5.0.6 on 2024-07-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mk', '0003_remove_producto_foto_url_producto_foto'),
    ]

    operations = [

    ]
