# Generated by Django 5.0.6 on 2024-07-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mk', '0004_remove_producto_id_producto_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='talla',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('TU', 'Talla Única')], max_length=2),
        ),
    ]
